version: 0.2

env:
  variables:
    AWS_REGION: "us-east-1"
    AWS_ACCOUNT_ID: "528757798791"
    REPO_NAME: "intellpulse-api"
    IMAGE_TAG: "latest"

    # Functions
    STG_FN: "intellpulse-api-staging"
    PROD_FN: "intellpulse-api"

phases:
  pre_build:
    commands:
      - "set -eu"
      - "echo Logging in to ECR..."
      - "aws ecr get-login-password --region \"$AWS_REGION\" | docker login --username AWS --password-stdin \"$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com\""

  build:
    commands:
      - "set -eu"
      - "echo Building Docker image..."
      - "docker build -t \"$REPO_NAME:$IMAGE_TAG\" ."
      - "docker tag \"$REPO_NAME:$IMAGE_TAG\" \"$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO_NAME:$IMAGE_TAG\""

  post_build:
    commands:
      - "set -euo pipefail"

      - "ECR_IMAGE=\"$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO_NAME:$IMAGE_TAG\""
      - "echo Pushing image to ECR: $ECR_IMAGE"
      - "docker push \"$ECR_IMAGE\""

      - "echo Resolving pushed image digest URI from Docker..."
      - "IMAGE_URI=\"$(docker inspect --format='{{index .RepoDigests 0}}' \"$ECR_IMAGE\")\""
      - "test -n \"$IMAGE_URI\""
      - "echo IMAGE_URI resolved (hidden digest)"

      - "echo Deploying to STAGING: $STG_FN"
      - "aws lambda update-function-code --function-name \"$STG_FN\" --region \"$AWS_REGION\" --image-uri \"$IMAGE_URI\""
      - "aws lambda wait function-updated --function-name \"$STG_FN\" --region \"$AWS_REGION\""

      - "STG_URL=\"$(aws lambda get-function-url-config --function-name \"$STG_FN\" --region \"$AWS_REGION\" --query 'FunctionUrl' --output text | sed 's:/*$::')\""
      - "echo STG_URL=$STG_URL"

      - "echo Smoke: /health (expect 200)"
      - "curl --globoff -fsS \"$STG_URL/health\" | grep -q '\"status\"'"

      # 1) Auth must be enforced (best = 401). If you purposely fail-closed when API_KEY missing, accept 500 too.
      - "echo Smoke: /signal WITHOUT key (expect 401; accept 500 only if API_KEY missing)"
      - "HTTP_CODE_NO_KEY=\"$(curl --globoff --retry 8 --retry-all-errors --retry-delay 1 -sS -o /tmp/signal_no_key.json -w '%{http_code}' \"$STG_URL/signal?asset=BTC-USD&mode=combined\" || true)\""
      - "echo HTTP_CODE_NO_KEY=$HTTP_CODE_NO_KEY"
      - |
        if [ "$HTTP_CODE_NO_KEY" = "401" ]; then
          echo "OK: auth enforced (401)"
        elif [ "$HTTP_CODE_NO_KEY" = "500" ]; then
          echo "OK: fail-closed when API_KEY missing (500)"
          cat /tmp/signal_no_key.json || true
        else
          echo "FAIL: expected 401 (or 500 if misconfigured), got $HTTP_CODE_NO_KEY"
          cat /tmp/signal_no_key.json || true
          exit 1
        fi

      # 2) Authenticated request using the API_KEY stored on the STG Lambda env (do NOT print it)
      - "API_KEY=\"$(aws lambda get-function-configuration --function-name \"$STG_FN\" --region \"$AWS_REGION\" --query 'Environment.Variables.API_KEY' --output text)\""
      - |
        if [ -z "$API_KEY" ] || [ "$API_KEY" = "None" ]; then
          echo "WARN: STG API_KEY is not set; skipping authenticated /signal smoke test"
        else
          echo "Smoke: /signal WITH key (accept 200 or 429)"
          HTTP_CODE_AUTH="$(curl --globoff --retry 8 --retry-all-errors --retry-delay 1 -sS -o /tmp/signal_auth.json -w '%{http_code}' -H "x-api-key: $API_KEY" "$STG_URL/signal?asset=BTC-USD&mode=combined" || true)"
          echo "HTTP_CODE_AUTH=$HTTP_CODE_AUTH"
          if [ "$HTTP_CODE_AUTH" = "200" ]; then
            grep -q '"latest_signal_text"' /tmp/signal_auth.json
            grep -q '"asset":"BTC-USD"' /tmp/signal_auth.json
            echo "OK: authenticated /signal (200)"
          elif [ "$HTTP_CODE_AUTH" = "429" ]; then
            echo "OK: authenticated /signal (429 quota/rate-limit)"
            cat /tmp/signal_auth.json || true
          else
            echo "FAIL: authenticated /signal expected 200/429, got $HTTP_CODE_AUTH"
            cat /tmp/signal_auth.json || true
            exit 1
          fi
        fi

      - "echo Deploying to PROD: $PROD_FN"
      - "aws lambda update-function-code --function-name \"$PROD_FN\" --region \"$AWS_REGION\" --image-uri \"$IMAGE_URI\""
      - "aws lambda wait function-updated --function-name \"$PROD_FN\" --region \"$AWS_REGION\""

      - "echo Done: deployed STG + PROD"
