version: 0.2

env:
  variables:
    AWS_REGION: "us-east-1"
    AWS_ACCOUNT_ID: "528757798791"
    REPO_NAME: "intellpulse-api"
    IMAGE_TAG: "latest"
    STG_FN: "intellpulse-api-staging"
    PROD_FN: "intellpulse-api"
    # set to "1" in CodeBuild env vars when you're ready
    DEPLOY_PROD: "0"

phases:
  pre_build:
    commands:
      - set -eux
      - echo "Logging in to ECR..."
      - aws ecr get-login-password --region "$AWS_REGION" | docker login --username AWS --password-stdin "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com"

  build:
    commands:
      - set -eux
      - echo "Building Docker image..."
      - docker build -t "$REPO_NAME:$IMAGE_TAG" .
      - docker tag "$REPO_NAME:$IMAGE_TAG" "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO_NAME:$IMAGE_TAG"

  post_build:
    commands:
      - |
        set -eux

        echo "Pushing image to ECR..."
        docker push "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO_NAME:$IMAGE_TAG"

        echo "Resolving ECR digest..."
        DIGEST="$(aws ecr describe-images \
          --region "$AWS_REGION" \
          --repository-name "$REPO_NAME" \
          --image-ids imageTag="$IMAGE_TAG" \
          --query "imageDetails[0].imageDigest" \
          --output text)"
        echo "New digest: $DIGEST"

        echo "Deploying to STAGING: $STG_FN"
        aws lambda update-function-code \
          --function-name "$STG_FN" \
          --region "$AWS_REGION" \
          --image-uri "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO_NAME@$DIGEST"
        aws lambda wait function-updated --function-name "$STG_FN" --region "$AWS_REGION"

        STG_URL="$(aws lambda get-function-url-config \
          --function-name "$STG_FN" \
          --region "$AWS_REGION" \
          --query "FunctionUrl" \
          --output text | sed 's:/*$::')"
        echo "STG_URL=$STG_URL"

        API_KEY="$(aws lambda get-function-configuration \
          --function-name "$STG_FN" \
          --region "$AWS_REGION" \
          --query "Environment.Variables.API_KEY" \
          --output text || true)"
        test -n "$API_KEY"
        echo "Loaded API_KEY for staging (hidden)"

        echo "Smoke: /health"
        curl --globoff -fsS "$STG_URL/health" | grep -q '"status"'

        echo "Smoke: /debug/cache/read"
        DEBUG_HTTP_CODE="$(curl --globoff -sS -o /tmp/debug.json -w "%{http_code}" \
          -H "x-api-key: $API_KEY" \
          "$STG_URL/debug/cache/read?asset=BTC-USD&mode=combined")"
        echo "DEBUG_HTTP_CODE=$DEBUG_HTTP_CODE"
        cat /tmp/debug.json || true
        test "$DEBUG_HTTP_CODE" = "200"
        grep -q '"enabled"' /tmp/debug.json

        echo "Smoke: /signal (accept 200 or 429)"
        HTTP_CODE="$(curl --globoff -sS -o /tmp/signal.json -w "%{http_code}" \
          -H "x-api-key: $API_KEY" \
          "$STG_URL/signal?asset=BTC-USD&mode=combined")"
        echo "HTTP_CODE=$HTTP_CODE"
        cat /tmp/signal.json || true
        if [ "$HTTP_CODE" = "200" ]; then
          grep -q '"latest_signal_text"' /tmp/signal.json
          grep -q '"asset":"BTC-USD"' /tmp/signal.json
          echo "Staging /signal OK (200)"
        elif [ "$HTTP_CODE" = "429" ]; then
          echo "Staging /signal OK (429)"
        else
          echo "Staging /signal FAILED ($HTTP_CODE)"
          exit 1
        fi

        echo "STAGING OK"

        if [ "${DEPLOY_PROD:-0}" != "1" ]; then
          echo "Skipping PROD deploy (DEPLOY_PROD!=1)."
          exit 0
        fi

        echo "Deploying to PROD: $PROD_FN"
        aws lambda update-function-code \
          --function-name "$PROD_FN" \
          --region "$AWS_REGION" \
          --image-uri "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO_NAME@$DIGEST"
        aws lambda wait function-updated --function-name "$PROD_FN" --region "$AWS_REGION"

        aws lambda get-function \
          --function-name "$PROD_FN" \
          --region "$AWS_REGION" \
          --query "Code.ImageUri" \
          --output text
