version: 0.2

env:
  variables:
    AWS_REGION: "us-east-1"
    AWS_ACCOUNT_ID: "528757798791"
    REPO_NAME: "intellpulse-api"
    IMAGE_TAG: "latest"
    STG_FN: "intellpulse-api-staging"
    STG_URL: "https://hrimhqter7wxdiwzcwiwmo5ubu0xplqb.lambda-url.us-east-1.on.aws"
    PROD_FN: "intellpulse-api"

phases:
  pre_build:
    commands:
      - "set -eu"
      - "echo \"Logging in to ECR...\""
      - "aws ecr get-login-password --region \"$AWS_REGION\" | docker login --username AWS --password-stdin \"$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com\""

  build:
    commands:
      - "set -eu"
      - "echo \"Building Docker image...\""
      - "docker build -t \"$REPO_NAME:$IMAGE_TAG\" ."
      - "docker tag \"$REPO_NAME:$IMAGE_TAG\" \"$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO_NAME:$IMAGE_TAG\""

  post_build:
    commands:
      - "set -eu"
      - "echo \"Pushing image to ECR...\""
      - "docker push \"$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO_NAME:$IMAGE_TAG\""
      - "DIGEST=$(aws ecr describe-images --region \"$AWS_REGION\" --repository-name \"$REPO_NAME\" --image-ids imageTag=\"$IMAGE_TAG\" --query \"imageDetails[0].imageDigest\" --output text)"
      - "echo \"New digest: $DIGEST\""

      - "echo \"Deploying to STAGING: $STG_FN\""
      - "STG_PREV_URI=$(aws lambda get-function --function-name \"$STG_FN\" --region \"$AWS_REGION\" --query \"Code.ImageUri\" --output text)"
      - "echo \"STAGING_PREVIOUS_IMAGE_URI=$STG_PREV_URI\""
      - "aws lambda update-function-code --function-name \"$STG_FN\" --region \"$AWS_REGION\" --image-uri \"$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO_NAME@$DIGEST\""
      - "aws lambda wait function-updated --function-name \"$STG_FN\" --region \"$AWS_REGION\" || true"
      - "echo \"Staging smoke test: /signal\""
      - "RESP=$(curl -fsS \"$STG_URL/signal?asset=BTC-USD&mode=combined\")"
      - "echo \"$RESP\""
      - "echo \"$RESP\" | grep -q '\"latest_signal_text\"' "
      - "echo \"$RESP\" | grep -q '\"asset\":\"BTC-USD\"' "
      - "echo \"Staging smoke test OK\""
      - "echo \"Deploying to PROD: $PROD_FN\""
      - "PROD_PREV_URI=$(aws lambda get-function --function-name \"$PROD_FN\" --region \"$AWS_REGION\" --query \"Code.ImageUri\" --output text)"
      - "echo \"PROD_PREVIOUS_IMAGE_URI=$PROD_PREV_URI\""
      - "aws lambda update-function-code --function-name \"$PROD_FN\" --region \"$AWS_REGION\" --image-uri \"$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO_NAME@$DIGEST\""
      - "aws lambda wait function-updated --function-name \"$PROD_FN\" --region \"$AWS_REGION\" || true"
      - "aws lambda get-function --function-name \"$PROD_FN\" --region \"$AWS_REGION\" --query \"Code.ImageUri\" --output text"
