version: 0.2

env:
  variables:
    AWS_REGION: "us-east-1"
    AWS_ACCOUNT_ID: "528757798791"
    REPO_NAME: "intellpulse-api"
    IMAGE_TAG: "latest"
    STG_FN: "intellpulse-api-staging"
    STG_URL: "https://hrimhqter7wxdiwzcwiwmo5ubu0xplqb.lambda-url.us-east-1.on.aws"
    PROD_FN: "intellpulse-api"
    API_KEY: "REPLACE_ME_API_KEY"

phases:
  pre_build:
    commands:
      - "set -eu"
      - "echo \"Logging in to ECR...\""
      - "aws ecr get-login-password --region \"$AWS_REGION\" | docker login --username AWS --password-stdin \"$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com\""

  build:
    commands:
      - "set -eu"
      - "echo \"Building Docker image...\""
      - "docker build -t \"$REPO_NAME:$IMAGE_TAG\" ."
      - "docker tag \"$REPO_NAME:$IMAGE_TAG\" \"$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO_NAME:$IMAGE_TAG\""

  post_build:
    commands:
      - "set -eu"
      - "setopt NO_NOMATCH 2>/dev/null || true"

      - "echo \"Pushing image to ECR...\""
      - "docker push \"$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO_NAME:$IMAGE_TAG\""

      - "DIGEST=$(aws ecr describe-images --region \"$AWS_REGION\" --repository-name \"$REPO_NAME\" --image-ids imageTag=\"$IMAGE_TAG\" --query \"imageDetails[0].imageDigest\" --output text)"
      - "echo \"New digest: $DIGEST\""

      - "echo \"Deploying to STAGING: $STG_FN\""
      - "aws lambda wait function-updated --function-name \"$STG_FN\" --region \"$AWS_REGION\" || true"
      - "aws lambda update-function-code --function-name \"$STG_FN\" --region \"$AWS_REGION\" --image-uri \"$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO_NAME@$DIGEST\" || (aws lambda wait function-updated --function-name \"$STG_FN\" --region \"$AWS_REGION\" && aws lambda update-function-code --function-name \"$STG_FN\" --region \"$AWS_REGION\" --image-uri \"$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO_NAME@$DIGEST\")"
      - "aws lambda wait function-updated --function-name \"$STG_FN\" --region \"$AWS_REGION\" || true"

      # ✅ Non-billable smoke tests (won't consume quota / won't 429 due to quota)
      - "echo \"Staging smoke test: /health (public)\""
      - "curl -fsS \"${STG_URL%/}/health\" | grep -q '\"status\"'"

      - "echo \"Staging smoke test: /debug/cache/read (authenticated, non-billable)\""
      - "RESP2=$(curl -fsS -H \"x-api-key: $API_KEY\" \"${STG_URL%/}/debug/cache/read?asset=BTC-USD&mode=combined\")"
      - "echo \"$RESP2\" | grep -q '\"enabled\"'"
      - "echo \"Staging smoke tests OK\""

      - "echo \"Deploying to PROD: $PROD_FN\""
      - "aws lambda wait function-updated --function-name \"$PROD_FN\" --region \"$AWS_REGION\" || true"
      - "aws lambda update-function-code --function-name \"$PROD_FN\" --region \"$AWS_REGION\" --image-uri \"$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO_NAME@$DIGEST\" || (aws lambda wait function-updated --function-name \"$PROD_FN\" --region \"$AWS_REGION\" && aws lambda update-function-code --function-name \"$PROD_FN\" --region \"$AWS_REGION\" --image-uri \"$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPO_NAME@$DIGEST\")"
      - "aws lambda wait function-updated --function-name \"$PROD_FN\" --region \"$AWS_REGION\" || true"
      - "aws lambda get-function --function-name \"$PROD_FN\" --region \"$AWS_REGION\" --query \"Code.ImageUri\" --output text"
